10 hw css dinner list
viktor-beet-root/2-front-end pull request #86
Opened 2021-10-27 19:50 UTC by teddi90

2021-11-07 12:22 UTC, viktor-beet-root requested changes
нет ссылки на гитпейджес

2021-11-14 17:33 UTC, viktor-beet-root requested changes

2021-11-14 17:33 UTC, viktor-beet-root commented on students/oleg_slobodyan/2_homework_html5/1/main.js
> -function slidePlugin(activeSlide = 0) {
а зачем ты удалил эти файлы, их не нужно было удалять, так как если я это смежу, это будет удалено в финальной ветке)

2021-11-15 20:48 UTC, teddi90 commented on students/oleg_slobodyan/2_homework_html5/1/main.js
> -function slidePlugin(activeSlide = 0) {
Виправив код його і видалив main.js. можете мержити фінальна версія без JS

2021-11-21 19:52 UTC, merged